msm: camera: Fix compilation issue with LTS 6.6.17
Below compilation issue is observed while moving to LTS 6.6.17.

drivers/cam_sensor_module/cam_tpg/tpg_hw/tpg_hw.c:36:4: error: 'snprintf' will always be truncated; specified size is 12, but format string expands to at least 13 [-Werror,-Wfortify-source]

drivers/cam_sensor_module/cam_tpg/tpg_hw/tpg_hw.c:41:3: error: 'snprintf' will always be truncated; specified size is 9, but format string expands to at least 10 [-Werror,-Wfortify-source]

drivers/cam_utils/cam_io_util.c:257:4: error: 'snprintf' will always be truncated; specified size is 12, but format string expands to at least 13 [-Werror,-Wfortify-source]

drivers/cam_utils/cam_io_util.c:262:3: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 11 [-Werror,-Wfortify-source]

Fix the issues by using right size.

Change-Id: I9b420d237727ad9a61c02bcc78bc696e66bf88c6
Signed-off-by: Satya Durga Srinivasu Prabhala <quic_satyap@quicinc.com>